{% set name = "openpnm" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 941cced9ef310d5d71965608ff0a3ffcc5cf4271339b51095bf6945c1cdd17d4

build:
  number: 1
  skip: true  # [py<311 or py>=314]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - hatchling
  run:
    - python
    - docrep >=0.3.2
    - h5py >=3.14.0
    - jsonschema >=4.25.1
    - llvmlite >=0.44
    - matplotlib >=3.10.6
    - matplotlib-inline >=0.1.7
    - networkx >=3.5
    - numba >=0.61
    - numpy <2.2
    - pandas >=2.3.2
    - pyamg >=5.3.0
    - pypardiso  # [linux64 or win64]
    - rich >=14.1.0
    - scikit-image >=0.25.0
    - scipy >=1.16.2
    - sympy >=1.14.0
    - thermo >=0.4.2
    - tqdm >=4.67.1
    - transforms3d >=0.4.2
test:
  requires:
    - python
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://pmeal.github.io/OpenPNM/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
